services:
  - type: background
    name: vahableecherbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
    secretFiles:
      - source: token.json
        mountPath: /etc/secrets/token.json
      - source: credentials.json
        mountPath: /etc/secrets/credentials.json
