services:
  - type: worker
    name: vahableecherbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false