services:
  - type: worker
    name: vahableecherbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python mail.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: <توکن_ربات>
      - key: OWNER_ID
        value: <آیدی_تلگرام_خودت>
