services:
  - type: background
    name: vahableecherbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: <توکن_تلگرام>
      - key: OWNER_ID
        value: <آیدی_مالک>
